### ISSUE TITLE
Game does not end when reaching 0 apples

### ISSUE THREAD

**Issue by rnestler** [lislis/manzana-attack#1]
As discussed at [RustFest](http://2017.rustfest.eu/talks/) :smiley: 
![manzana](https://cloud.githubusercontent.com/assets/1435346/25575270/0fa019b0-2e56-11e7-8837-6615c8a858a9.png)

**Comment by lislis** [comment]
@rnestler with your fix for not shooting unlimited apples in place, the game should end when the last apple reaches the floor. right?

**Comment by rnestler** [comment]
Yes, the game will end after the 10th apple reaches the floor, but one is able to shoot more in the meantime.

**Comment by lislis** [comment]
This commit should fix the infinite apple shooting bug e2c23684f3e2d58dc21704862fc4cea37a427f8d
I think this can be closed now!
